(() => {
 const api='https://tvm-licensing-api-prod.optiflowzoffice.workers.dev',testApi='https://tvm-licensing-api.optiflowzoffice.workers.dev',product='font_pirate_plus';
 async function post(path,body){const base=path==='/v1/checkout/result'&&body.sessionId?.startsWith('cs_test_')?testApi:api;const response=await fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product,...body}),signal:AbortSignal.timeout(15000)}),data=await response.json();if(!response.ok)throw new Error(data.error?.message||'Could not connect. Please try again.');return data;}
 const buy=document.getElementById('buy-plus');buy.onclick=async()=>{buy.disabled=true;buy.textContent='Opening checkout…';try{const result=await post('/v1/checkout',{plan:'lifetime'});if(new URL(result.url).hostname!=='checkout.stripe.com')throw new Error('Invalid checkout address.');location.assign(result.url);}catch(e){document.getElementById('plus-checkout-error').textContent=e.message;buy.disabled=false;buy.textContent='Get Font Pirate Plus';}};
 document.getElementById('fp-billing').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const result=await post('/v1/billing/portal',{licenseKey:document.getElementById('fp-billing-key').value.trim()});if(new URL(result.url).hostname!=='billing.stripe.com')throw new Error('Invalid billing address.');location.assign(result.url);}catch(e){document.getElementById('fp-billing-status').textContent=e.message;b.disabled=false;}};
 const dialog=document.getElementById('fp-checkout-result'),params=new URLSearchParams(location.search),sessionId=params.get('session_id');
 document.getElementById('fp-close-result').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{if(document.getElementById('fp-result-license').hidden)return;const u=new URL(location);u.searchParams.delete('checkout');u.searchParams.delete('session_id');history.replaceState({},'',u.pathname+u.search+u.hash);});
 document.getElementById('fp-copy-key').onclick=async()=>{const key=document.getElementById('fp-result-key');try{await navigator.clipboard.writeText(key.textContent);document.getElementById('fp-copy-key').textContent='Copied';}catch{const range=document.createRange();range.selectNodeContents(key);getSelection().removeAllRanges();getSelection().addRange(range);}};
 if(params.get('checkout')==='success'&&sessionId){dialog.showModal();document.getElementById('fp-result-message').textContent='Confirming your payment…';post('/v1/checkout/result',{sessionId}).then(result=>{if(result.product!==product)throw new Error('This purchase belongs to another extension.');document.getElementById('fp-result-title').textContent='Welcome to Plus.';document.getElementById('fp-result-message').textContent='Save your key, then activate it in Font Pirate.';document.getElementById('fp-result-key').textContent=result.licenseKey;document.getElementById('fp-result-license').hidden=false;}).catch(e=>{document.getElementById('fp-result-title').textContent='Your license is not ready yet';document.getElementById('fp-result-message').textContent=e.message+' Refresh this page to retry, or contact support with your Stripe receipt.';});}
 if(params.get('checkout')==='cancelled'){document.getElementById('plus-checkout-error').textContent='Checkout was cancelled. No payment was made.';document.getElementById('plus').scrollIntoView();}
})();
